### ISSUE TITLE
Challenge 0

### ISSUE THREAD

**Issue by LuongXuanNhat** [chunhanhoa/J2YB#1]
Bạn ơi, ở slide topic 2 có sai chính tả nè bạn. Mà bạn làm slide tốt ghê 
![image](https://github.com/chunhanhoa/J2YB/assets/96036623/73103cd1-a569-4fd8-9a0a-a56dc8bfdb8a)

**Comment by chunhanhoa** [comment]
Dạ để em sửa và nộp lại ạ
